In [6]:
import tensorflow.compat.v1 as tf
import numpy as np

tf.disable_eager_execution()
tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name="bias")

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(221):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={
        X: x_data, Y: y_data
    })
    if step % 10 == 0 :
        print(step, '번 째: ', cost_val)
        print(step, '번 째: ', hy_val)

#ask my score
print('내 예상 점수는? ', sess.run(hypothesis, feed_dict={
    X: [[90., 87., 100.]]
}))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 25
0 번 째:  207488.16
0 번 째:  [[-270.7529 ]
 [-330.78342]
 [-323.07275]
 [-354.08548]
 [-251.55775]
 [-189.12744]
 [-266.54678]
 [-199.6378 ]
 [-312.901  ]
 [-294.96216]
 [-256.1025 ]
 [-255.61302]
 [-331.70108]
 [-272.85117]
 [-268.78613]
 [-337.25223]
 [-258.80313]
 [-320.23584]
 [-315.0468 ]
 [-281.62057]
 [-312.7131 ]
 [-312